FROM confluentinc/cp-kafka-connect-base:6.0.1

RUN confluent-hub install --no-prompt confluentinc/kafka-connect-s3:10.0.2 \
   && confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.2.3 \
   && confluent-hub install --no-prompt confluentinc/kafka-connect-datagen:0.5.0